const routes = [
  {
    path: '/main',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '', component: () => import('pages/main/DashboardPage.vue'), props: true },
      { path: 'noticeboard', name: 'noticeBoard', component: () => import('pages/main/NoticeBoard.vue'), props: true },

      { path: 'sal1010', component: () => import('pages/erp/sal/SalV1010.vue') },
      { path: 'sal1020', component: () => import('pages/erp/sal/SalV1020.vue') },
      { path: 'sal2010', component: () => import('pages/erp/sal/SalV2010.vue') },
      { path: 'sal2020', component: () => import('pages/erp/sal/SalV2020.vue') },
      { path: 'sal2030', component: () => import('pages/erp/sal/SalV2030.vue') },
      { path: 'sal2110', component: () => import('pages/erp/sal/SalV2110.vue') },
      { path: 'sal2120', component: () => import('pages/erp/sal/SalV2120.vue') },
      { path: 'sal2130', component: () => import('pages/erp/sal/SalV2130.vue') },
      { path: 'sal2140', component: () => import('pages/erp/sal/SalV2140.vue') },
      { path: 'sal2150', component: () => import('pages/erp/sal/SalV2150.vue') },
      { path: 'sal2160', component: () => import('pages/erp/sal/SalV2160.vue') },
      { path: 'sal2170', component: () => import('pages/erp/sal/SalV2170.vue') },
      { path: 'sal2180', component: () => import('pages/erp/sal/SalV2180.vue') },
      { path: 'sal2190', component: () => import('pages/erp/sal/SalV2190.vue') },
      { path: 'sal3010', component: () => import('pages/erp/sal/SalV3010.vue') },
      { path: 'sal3020', component: () => import('pages/erp/sal/SalV3020.vue') },
      { path: 'sal3110', component: () => import('pages/erp/sal/SalV3110.vue') },
      { path: 'sal3120', component: () => import('pages/erp/sal/SalV3120.vue') },
      { path: 'sal3210', component: () => import('pages/erp/sal/SalV3210.vue') },
      { path: 'sal3220', component: () => import('pages/erp/sal/SalV3220.vue') },
      { path: 'sal4110', component: () => import('pages/erp/sal/SalV4110.vue') },
      { path: 'sal4120', component: () => import('pages/erp/sal/SalV4120.vue') },
      { path: 'sal4130', component: () => import('pages/erp/sal/SalV4130.vue') },
      { path: 'sal4210', component: () => import('pages/erp/sal/SalV4210.vue') },
      { path: 'sal4220', component: () => import('pages/erp/sal/SalV4220.vue') },
      { path: 'sal4310', component: () => import('pages/erp/sal/SalV4310.vue') },
      { path: 'sal4320', component: () => import('pages/erp/sal/SalV4320.vue') },
      { path: 'sal4410', component: () => import('pages/erp/sal/SalV4410.vue') },
      { path: 'sal4420', component: () => import('pages/erp/sal/SalV4420.vue') },
      { path: 'sal4430', component: () => import('pages/erp/sal/SalV4430.vue') },
      { path: 'sal4440', component: () => import('pages/erp/sal/SalV4440.vue') },
      { path: 'sal4450', component: () => import('pages/erp/sal/SalV4450.vue') },
      { path: 'sal4460', component: () => import('pages/erp/sal/SalV4460.vue') },
      { path: 'sal4470', component: () => import('pages/erp/sal/SalV4470.vue') },
      { path: 'sal4480', component: () => import('pages/erp/sal/SalV4480.vue') },
      { path: 'sal4490', component: () => import('pages/erp/sal/SalV4490.vue') },

      { path: 'fee1010', component: () => import('pages/erp/fee/FeeV1010.vue') },
      { path: 'fee1020', component: () => import('pages/erp/fee/FeeV1020.vue') },
      { path: 'fee1030', component: () => import('pages/erp/fee/FeeV1030.vue') },
      { path: 'fee2010', component: () => import('pages/erp/fee/FeeV2010.vue') },
      { path: 'fee2020', component: () => import('pages/erp/fee/FeeV2020.vue') },
      { path: 'fee3010', component: () => import('pages/erp/fee/FeeV3010.vue') },
      { path: 'fee3020', component: () => import('pages/erp/fee/FeeV3020.vue') },
      { path: 'fee4010', component: () => import('pages/erp/fee/FeeV4010.vue') },
      { path: 'fee4020', component: () => import('pages/erp/fee/FeeV4020.vue') },
      { path: 'fee5010', component: () => import('pages/erp/fee/FeeV5010.vue') },
      { path: 'fee5020', component: () => import('pages/erp/fee/FeeV5020.vue') },

      { path: 'mst2010', component: () => import('pages/erp/mst/MstV2010.vue') },
      { path: 'mst2020', component: () => import('pages/erp/mst/MstV2020.vue') },
      { path: 'mst2030', component: () => import('pages/erp/mst/MstV2030.vue') },
      { path: 'mst2040', component: () => import('pages/erp/mst/MstV2040.vue') },
      { path: 'mst5090', component: () => import('pages/erp/mst/MstV5090.vue') },
      { path: 'mstgrid', component: () => import('pages/erp/mst/MstVgrid.vue') },
      { path: 'mstgridfocus', component: () => import('pages/erp/mst/MstVgridFocus.vue') },
      { path: 'mstprint', component: () => import('pages/erp/mst/MstVprint.vue') },
      { path: 'mstexcel', component: () => import('pages/erp/mst/MstVexcel.vue') },
      { path: 'mstgps', component: () => import('pages/erp/mst/MstVgps.vue') },
      { path: 'mstvoice', component: () => import('pages/erp/mst/MstVvoice.vue') },
      { path: 'msteditor', component: () => import('pages/erp/mst/MstVeditor.vue') },
      { path: 'stepEdit', component: () => import('pages/erp/mst/STEP_EDIT.vue') },

      { path: 'sys1010', component: () => import('pages/erp/sys/SysV1010.vue') },
      { path: 'sys4020', component: () => import('pages/erp/sys/SysV4020.vue') },
      { path: 'sys4030', component: () => import('pages/erp/sys/SysV4030.vue') },

      { path: 'com1010', component: () => import('pages/erp/com/ComV1010.vue') },
      { path: 'com1020', component: () => import('pages/erp/com/ComV1020.vue') },
      { path: 'com2010', component: () => import('pages/erp/com/ComV2010.vue') },
      { path: 'com2020', component: () => import('pages/erp/com/ComV2020.vue') },
      { path: 'com2030', component: () => import('pages/erp/com/ComV2030.vue') },
      { path: 'com5010', component: () => import('pages/erp/com/ComV5010.vue') },
      { path: 'com5020', component: () => import('pages/erp/com/ComV5020.vue') },
      { path: 'com8010', component: () => import('pages/erp/com/ComV8010.vue') },
      { path: 'com9090', component: () => import('pages/erp/com/ComV9090.vue') },

      {
        path: 'profile',
        component: () => import('pages/profile/ProfilePage.vue'),
        children: [
          { path: '', component: () => import('pages/profile/ProfilePosts.vue') },
          { path: 'saved', component: () => import('pages/profile/ProfileSaved.vue') },
          { path: 'tagged', component: () => import('pages/profile/ProfileTagged.vue') },
        ],
      },
    ],
  },
  {
    path: '/',
    component: () => import('layouts/AuthLayout.vue'),
    children: [
      { path: '', component: () => import('pages/auth/SignIn.vue') },
      { path: 'sign-up', component: () => import('pages/auth/SignUp.vue') },
    ],
  },

  // Always leave this as last one,
  // but you can also remove it
  {
    path: '/:catchAll(.*)*',
    component: () => import('pages/ErrorNotFound.vue'),
  },
];

export default routes;
